### PR TITLE
Using `teal_data` in the modules instead of `tdata`

### PR DESCRIPTION
**Pull request by vedhav**
This is a feature branch, **DON'T MERGE**. PR open to have a constant checks. We will start review this PR as a whole in the sprint 4.

```r
staged.dependencies::dependency_table(
  project = "insightsengineering/teal.modules.hermes@https://github.com",
  project_type = "repo@host",
  ref = "refactor",
  verbose = 1
) |>
staged.dependencies::install_deps()
```

### CODE REVIEW

**Comment by kartikeyakirar** [comment]
> This is a feature branch, DON'T MERGE and DON'T COMMENT
All the changes for module are here , so making comments on this branch

**Review by kartikeyakirar — CHANGES_REQUESTED** [review]
@vedhav, could you please include the package calls` teal.data::join_keys `and `teal.data::datanames` in all places?

**Review by kartikeyakirar — CHANGES_REQUESTED** [review]
@vedhav, I noticed that the examples in `geneSpec.R` and` sampleVarSpec.R` are still using `tdata`  causing them to fail. Could you please update these either in the same branch or as a separate issue?

**Comment by vedhav** [comment]
Raised a PR #345 that will unblock this

**Comment by vedhav** [comment]
> @vedhav, could you please include the package callsteal.data::join_keysand teal.data::datanames in all places?

@kartikeyakirar I think it can be handled in a separate issue, We are calling it without namespace in other packages too. And this is more of a coding standard issue instead of `tdata` -> `teal_data` refactor issue so maybe we don't creep up this issue.

**Comment by pawelru** [comment]
Hi guys.

We have integration test failures probably because this has not been merged

```
* checking R code for possible problems ... NOTE
sample_tm_g_forest_tte: no visible global function definition for
  ‘teal_data’
sample_tm_g_forest_tte: no visible global function definition for
  ‘datanames<-’
sample_tm_g_forest_tte: no visible global function definition for
  ‘join_keys’
sample_tm_g_forest_tte: no visible global function definition for
  ‘join_keys<-’
sample_tm_g_km: no visible global function definition for ‘teal_data’
sample_tm_g_km: no visible global function definition for ‘datanames<-’
sample_tm_g_km: no visible global function definition for ‘join_keys’
sample_tm_g_km: no visible global function definition for ‘join_keys<-’
Undefined global functions or variables:
  datanames<- join_keys join_keys<- teal_data
```

Can we please prioritise it? Please discuss on the daily.

**Comment by donyunardi** [comment]
> Hi guys.
> 
> We have integration test failures probably because this has not been merged
> 
> ```
> * checking R code for possible problems ... NOTE
> sample_tm_g_forest_tte: no visible global function definition for
>   ‘teal_data’
> sample_tm_g_forest_tte: no visible global function definition for
>   ‘datanames<-’
> sample_tm_g_forest_tte: no visible global function definition for
>   ‘join_keys’
> sample_tm_g_forest_tte: no visible global function definition for
>   ‘join_keys<-’
> sample_tm_g_km: no visible global function definition for ‘teal_data’
> sample_tm_g_km: no visible global function definition for ‘datanames<-’
> sample_tm_g_km: no visible global function definition for ‘join_keys’
> sample_tm_g_km: no visible global function definition for ‘join_keys<-’
> Undefined global functions or variables:
>   datanames<- join_keys join_keys<- teal_data
> ```
> 
> Can we please prioritise it? Please discuss on the daily.

it's odd to see this NOTE during daily integration test but not in this PR.
Addressing the issue with: https://github.com/insightsengineering/teal.modules.hermes/issues/346

**Pull request merged**
